/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLiSinhVien.Jrame;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class JFM_SinhVien extends javax.swing.JFrame {

    /**
     * Creates new form JFM_SinhVien
     */
    DefaultTableModel dftb = new DefaultTableModel();
    int checkTT=0;
    public JFM_SinhVien() {
        initComponents();
        loadData();
        getContentPane().setBackground(Color.PINK);
    }
    private void loadData() {

        try {
            Connect a = new Connect();
            Connection con = a.getConnection();
            String sql = "SELECT * FROM SinhVien";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            ResultSetMetaData meta = rs.getMetaData();
            int n = meta.getColumnCount();
            Vector col = new Vector();
            col.add("Mã sinh viên");
            col.add("Họ tên sinh viên");
            col.add("Ngành học");
            col.add("Ngày sinh");
            col.add("Giới tính");
            col.add("Địa chỉ");
            dftb.setColumnIdentifiers(col);
            while (rs.next()) {
                Vector row = new Vector();
                for (int i = 0; i < n; i++) {
                    if (i < n) {
                        row.addElement(rs.getString(i + 1));
                    } else {
                    }
                }
                dftb.addRow(row);

            }
            tblSV.setModel(dftb);
            tblSV.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    if (tblSV.getSelectedRow() >= 0) {
                        txtMaSV.setText(tblSV.getValueAt(tblSV.getSelectedRow(), 0).toString());
                        txtTenSV.setText(tblSV.getValueAt(tblSV.getSelectedRow(), 1).toString());
                        txtMaKhoa.setText(tblSV.getValueAt(tblSV.getSelectedRow(), 2).toString());
                        txtNgaySinh.setText(tblSV.getValueAt(tblSV.getSelectedRow(), 3).toString());
                        String s = tblSV.getValueAt(tblSV.getSelectedRow(), 4).toString();
                        if (s.equals("1")) {
                            rbNam.setSelected(true);
                        } else {
                            rbNu.setSelected(true);
                        }
                        txtQueQuan.setText(tblSV.getValueAt(tblSV.getSelectedRow(), 5).toString());
                    }
                }
            });
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Lỗi : " + ex);
            Logger.getLogger(Connection.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbMaSV = new javax.swing.JLabel();
        lbTenSV = new javax.swing.JLabel();
        lbGioiTinh = new javax.swing.JLabel();
        lbNgaySinh = new javax.swing.JLabel();
        lbQueQuan = new javax.swing.JLabel();
        lbMaLop = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtQueQuan = new javax.swing.JTextField();
        txtTenSV = new javax.swing.JTextField();
        txtMaKhoa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btDau = new javax.swing.JButton();
        btTruoc = new javax.swing.JButton();
        btSau = new javax.swing.JButton();
        btCuoi = new javax.swing.JButton();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btLuu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSV = new javax.swing.JTable();
        rbNam = new javax.swing.JRadioButton();
        rbNu = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbMaSV.setText("Mã Sinh Viên: ");

        lbTenSV.setText("Tên Sinh Viên");

        lbGioiTinh.setText("Giới tính");

        lbNgaySinh.setText("Ngày sinh: ");

        lbQueQuan.setText("Quê quán");

        lbMaLop.setText("Ngành học:");

        txtMaSV.setBackground(new java.awt.Color(255, 204, 204));
        txtMaSV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtNgaySinh.setBackground(new java.awt.Color(255, 204, 204));
        txtNgaySinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtQueQuan.setBackground(new java.awt.Color(255, 204, 204));
        txtQueQuan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtQueQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQueQuanActionPerformed(evt);
            }
        });

        txtTenSV.setBackground(new java.awt.Color(255, 204, 204));
        txtTenSV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtMaKhoa.setBackground(new java.awt.Color(255, 204, 204));
        txtMaKhoa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("THÔNG TIN SINH VIÊN");

        btDau.setBackground(new java.awt.Color(255, 204, 204));
        btDau.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btDau.setText("Đầu");
        btDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDauActionPerformed(evt);
            }
        });

        btTruoc.setBackground(new java.awt.Color(255, 204, 204));
        btTruoc.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btTruoc.setText("Trước");
        btTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTruocActionPerformed(evt);
            }
        });

        btSau.setBackground(new java.awt.Color(255, 204, 204));
        btSau.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btSau.setText("Sau");
        btSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSauActionPerformed(evt);
            }
        });

        btCuoi.setBackground(new java.awt.Color(255, 204, 204));
        btCuoi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btCuoi.setText("Cuối");
        btCuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCuoiActionPerformed(evt);
            }
        });

        btThem.setBackground(new java.awt.Color(255, 204, 204));
        btThem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setBackground(new java.awt.Color(255, 204, 204));
        btSua.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btXoa.setBackground(new java.awt.Color(255, 204, 204));
        btXoa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btLuu.setBackground(new java.awt.Color(255, 204, 204));
        btLuu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btLuu.setText("Lưu");
        btLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuActionPerformed(evt);
            }
        });

        tblSV.setBackground(new java.awt.Color(255, 231, 234));
        tblSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSV);

        rbNam.setText("Nam");

        rbNu.setText("Nữ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btSau, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btCuoi, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(btLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbMaLop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbQueQuan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNgaySinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbGioiTinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbMaSV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(lbTenSV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaSV)
                            .addComponent(txtTenSV)
                            .addComponent(txtNgaySinh)
                            .addComponent(txtQueQuan)
                            .addComponent(txtMaKhoa)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(rbNu)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMaSV)
                            .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTenSV))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMaLop)
                            .addComponent(txtMaKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbNam)
                            .addComponent(rbNu))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNgaySinh)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btDau)
                            .addComponent(btTruoc)
                            .addComponent(btSau)
                            .addComponent(btCuoi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btThem)
                            .addComponent(btSua)
                            .addComponent(btXoa)
                            .addComponent(btLuu)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQueQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQueQuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQueQuanActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        txtMaSV.enable(true);
        txtMaKhoa.enable(true);
        txtQueQuan.enable(true);
        txtNgaySinh.enable(true);
        txtTenSV.enable(true);
        buttonGroup1.clearSelection();
        
        txtTenSV.setText("");
        txtNgaySinh.setText("");
        txtQueQuan.setText("");
        txtMaKhoa.setText("");
        txtMaSV.setText("");
        txtMaSV.requestFocus();
        checkTT=1;
    }//GEN-LAST:event_btThemActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here: try {
        try{
            Connect  a = new Connect();
            Connection con = a.getConnection();
            String sql = "DELETE FROM SinhVien WHERE MaSV=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, txtMaSV.getText());
            ps.executeUpdate();
            dftb.setRowCount(0);
            loadData();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không xóa được sinh viên");
            Logger.getLogger(Connection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        checkTT=2;
            txtNgaySinh.enable(true);
            txtTenSV.enable(true);
            txtQueQuan.enable(true);
            txtNgaySinh.enable(true);
            txtMaKhoa.enable(true);
    }//GEN-LAST:event_btSuaActionPerformed

    private void btLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuActionPerformed
        // TODO add your handling code here:
        if(checkTT==1)
       {
            try {
            Connect a = new Connect();
            Connection con = a.getConnection();
            String sql = "INSERT INTO SINHVIEN values(?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, txtMaSV.getText());
            ps.setString(2, txtTenSV.getText());
            ps.setString(3, txtMaKhoa.getText());
            ps.setString(4, txtNgaySinh.getText());
            ps.setBoolean(5, rbNam.isSelected() ? true : false);
            ps.setString(6, txtQueQuan.getText());
            ps.executeUpdate();
            dftb.setRowCount(0);
            loadData();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không thể thêm sinh viên");
//            Logger.getLogger(Connection.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(checkTT==2)
       {
             try {
            Connect a = new Connect();
            Connection con = a.getConnection();
            String sql = "UPDATE SINHVIEN SET HoTen = ?,maKhoa = ?,NgaySinh = ?,GioiTinh = ?,DiaChi= ? where MaSV = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, txtTenSV.getText());
            ps.setString(2, txtMaKhoa.getText());
            ps.setString(3, txtNgaySinh.getText());
            ps.setBoolean(4, rbNam.isSelected() ? true : false);
            ps.setString(5, txtQueQuan.getText());
            ps.setString(6, txtMaSV.getText());
            ps.executeUpdate();
            dftb.setRowCount(0);
            loadData();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không update được sinh viên");
            Logger.getLogger(Connection.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        txtMaSV.enable(false);
        txtMaKhoa.enable(false);
        txtQueQuan.enable(false);
        txtNgaySinh.enable(false);
        txtTenSV.enable(false);
    }//GEN-LAST:event_btLuuActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtMaSV.enable(false);
        txtMaKhoa.enable(false);
        txtQueQuan.enable(false);
        txtNgaySinh.enable(false);
        txtTenSV.enable(false);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        new JFM_Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDauActionPerformed
        // TODO add your handling code here:
        getSelectFirst();
    }//GEN-LAST:event_btDauActionPerformed

    private void btTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTruocActionPerformed
        // TODO add your handling code here:
        getSelectPrevious();
    }//GEN-LAST:event_btTruocActionPerformed

    private void btSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSauActionPerformed
        // TODO add your handling code here:
        getSelectNext();
    }//GEN-LAST:event_btSauActionPerformed

    private void btCuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCuoiActionPerformed
        // TODO add your handling code here:
        getSelectLast();
    }//GEN-LAST:event_btCuoiActionPerformed

    public void getSelectFirst(){
            int selectedRow= 0;
            txtMaSV.setText(tblSV.getValueAt(selectedRow, 0).toString());
            txtTenSV.setText(tblSV.getValueAt(selectedRow,1).toString());
            txtMaKhoa.setText(tblSV.getValueAt(selectedRow, 2).toString());
            txtNgaySinh.setText(tblSV.getValueAt(selectedRow, 3).toString());
            String s = tblSV.getValueAt(selectedRow, 4).toString();
            if (s.equals("1")) {
            rbNam.setSelected(true);
            } else {
            rbNu.setSelected(true);
            }
            txtQueQuan.setText(tblSV.getValueAt(selectedRow, 5).toString());
            tblSV.setRowSelectionInterval(0, 0);
    }
    public void getSelectPrevious(){
        if(tblSV.getSelectedRow()>= 1){
            int selectedRow= tblSV.getSelectedRow()-1;
            txtMaSV.setText(tblSV.getValueAt(selectedRow, 0).toString());
            txtTenSV.setText(tblSV.getValueAt(selectedRow,1).toString());
            txtMaKhoa.setText(tblSV.getValueAt(selectedRow, 2).toString());
            txtNgaySinh.setText(tblSV.getValueAt(selectedRow, 3).toString());
            String s = tblSV.getValueAt(selectedRow, 4).toString();
            if (s.equals("1")) {
            rbNam.setSelected(true);
            } else {
            rbNu.setSelected(true);
            }
            txtQueQuan.setText(tblSV.getValueAt(selectedRow, 5).toString());
            tblSV.setRowSelectionInterval(selectedRow, selectedRow);
        }
    }
    public void getSelectNext(){
        if(tblSV.getSelectedRow()< tblSV.getRowCount()+1){
            int selectedRow= tblSV.getSelectedRow()+1;
            txtMaSV.setText(tblSV.getValueAt(selectedRow, 0).toString());
            txtTenSV.setText(tblSV.getValueAt(selectedRow,1).toString());
            txtMaKhoa.setText(tblSV.getValueAt(selectedRow, 2).toString());
            txtNgaySinh.setText(tblSV.getValueAt(selectedRow, 3).toString());
            String s = tblSV.getValueAt(selectedRow, 4).toString();
            if (s.equals("1")) {
            rbNam.setSelected(true);
            } else {
            rbNu.setSelected(true);
            }
            txtQueQuan.setText(tblSV.getValueAt(selectedRow, 5).toString());
            tblSV.setRowSelectionInterval(selectedRow, selectedRow);
        }
    }
    public void getSelectLast(){
            int selectedRow= tblSV.getRowCount()-1;
            txtMaSV.setText(tblSV.getValueAt(selectedRow, 0).toString());
            txtTenSV.setText(tblSV.getValueAt(selectedRow,1).toString());
            txtMaKhoa.setText(tblSV.getValueAt(selectedRow, 2).toString());
            txtNgaySinh.setText(tblSV.getValueAt(selectedRow, 3).toString());
            String s = tblSV.getValueAt(selectedRow, 4).toString();
            if (s.equals("1")) {
            rbNam.setSelected(true);
            } else {
            rbNu.setSelected(true);
            }
            txtQueQuan.setText(tblSV.getValueAt(selectedRow, 5).toString());
            tblSV.setRowSelectionInterval(0, 0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFM_Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCuoi;
    private javax.swing.JButton btDau;
    private javax.swing.JButton btLuu;
    private javax.swing.JButton btSau;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btTruoc;
    private javax.swing.JButton btXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbMaLop;
    private javax.swing.JLabel lbMaSV;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbQueQuan;
    private javax.swing.JLabel lbTenSV;
    private javax.swing.JRadioButton rbNam;
    private javax.swing.JRadioButton rbNu;
    private javax.swing.JTable tblSV;
    private javax.swing.JTextField txtMaKhoa;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtTenSV;
    // End of variables declaration//GEN-END:variables
}
